# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler_to_worker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scheduler_to_worker.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19scheduler_to_worker.proto\x1a\x0b\x65nums.proto\"-\n\nRunRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x04\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"9\n\x0bRunResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\x04\x12\x1a\n\x06status\x18\x02 \x01(\x0e\x32\n.JobStatus27\n\x11SchedulerToWorker\x12\"\n\x03Run\x12\x0b.RunRequest\x1a\x0c.RunResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[enums__pb2.DESCRIPTOR,])




_RUNREQUEST = _descriptor.Descriptor(
  name='RunRequest',
  full_name='RunRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='RunRequest.job_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='RunRequest.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=87,
)


_RUNRESPONSE = _descriptor.Descriptor(
  name='RunResponse',
  full_name='RunResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='RunResponse.job_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='RunResponse.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=146,
)

_RUNRESPONSE.fields_by_name['status'].enum_type = enums__pb2._JOBSTATUS
DESCRIPTOR.message_types_by_name['RunRequest'] = _RUNREQUEST
DESCRIPTOR.message_types_by_name['RunResponse'] = _RUNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunRequest = _reflection.GeneratedProtocolMessageType('RunRequest', (_message.Message,), dict(
  DESCRIPTOR = _RUNREQUEST,
  __module__ = 'scheduler_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:RunRequest)
  ))
_sym_db.RegisterMessage(RunRequest)

RunResponse = _reflection.GeneratedProtocolMessageType('RunResponse', (_message.Message,), dict(
  DESCRIPTOR = _RUNRESPONSE,
  __module__ = 'scheduler_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:RunResponse)
  ))
_sym_db.RegisterMessage(RunResponse)



_SCHEDULERTOWORKER = _descriptor.ServiceDescriptor(
  name='SchedulerToWorker',
  full_name='SchedulerToWorker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=148,
  serialized_end=203,
  methods=[
  _descriptor.MethodDescriptor(
    name='Run',
    full_name='SchedulerToWorker.Run',
    index=0,
    containing_service=None,
    input_type=_RUNREQUEST,
    output_type=_RUNRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULERTOWORKER)

DESCRIPTOR.services_by_name['SchedulerToWorker'] = _SCHEDULERTOWORKER

# @@protoc_insertion_point(module_scope)
