# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import scheduler_to_worker_pb2 as scheduler__to__worker__pb2


class SchedulerToWorkerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Run = channel.unary_unary(
        '/SchedulerToWorker/Run',
        request_serializer=scheduler__to__worker__pb2.RunRequest.SerializeToString,
        response_deserializer=scheduler__to__worker__pb2.RunResponse.FromString,
        )


class SchedulerToWorkerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Run(self, request, context):
    """Starts a job on a worker
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SchedulerToWorkerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Run': grpc.unary_unary_rpc_method_handler(
          servicer.Run,
          request_deserializer=scheduler__to__worker__pb2.RunRequest.FromString,
          response_serializer=scheduler__to__worker__pb2.RunResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SchedulerToWorker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
